const fs=require('fs'),vm=require('vm'),assert=require('assert');
let src=fs.readFileSync(require('path').join(__dirname,'../assets/app.js'),'utf8');
src=src.slice(0,src.indexOf('function setupStaticEvents(){'));
const node=()=>({innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){},toggle(){}},querySelector(){return node()},querySelectorAll(){return[]}});
const ctx={console,crypto:{randomUUID:()=>`test-${Math.random()}`},document:{querySelector:()=>node(),querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem(){}},confirm:()=>true,alert(){},Blob:function(){},URL:{createObjectURL(){return''},revokeObjectURL(){}},FileReader:function(){}};
vm.createContext(ctx);vm.runInContext(src+'\n;globalThis.__q={defaultProject,formulas,cmhcScore,normalizeProject,setState:x=>{state=x},getState:()=>state};',ctx);
function calc(mut){const st=ctx.__q.defaultProject();mut?.(st);ctx.__q.setState(st);return ctx.__q.formulas()}
function close(a,b,tol=1e-6){assert.ok(Math.abs(a-b)<=tol,`${a} != ${b}`)}
let count=0;function test(name,fn){try{fn();console.log('PASS',name);count++}catch(e){console.error('FAIL',name,e.message);process.exitCode=1}}

test('zero project remains finite',()=>{const f=calc(s=>{s.unitmix.units=[];s.returns.holdYears=0});for(const [k,v] of Object.entries(f))if(typeof v==='number')assert.ok(Number.isFinite(v),k)});
test('20-unit base revenue and NOI',()=>{const f=calc(s=>{s.unitmix.units=[['Studio',2,450,1400,1100,'Market'],['1 Bedroom',10,650,1750,1300,'Market'],['2 Bedroom',6,850,2200,1650,'Market'],['3 Bedroom',2,1050,2700,2000,'Market']];s.unitmix.otherIncome=12000;s.unitmix.vacancyPct=3;s.unitmix.stabilizedOccupancy=97;s.operations.expenses=[['x',158000]];s.operations.managementPct=4;s.operations.reservePerUnit=350;s.financing.includeCalculatedCarry='No'});close(f.monthlyRent,38900);close(f.residentialEgi,464436);close(f.residentialNoi,280858.56)});
test('affordable rent used only for affordable rows',()=>{const f=calc(s=>{s.unitmix.units=[['A',10,650,1750,1300,'Affordable A'],['B',2,800,2000,1000,'Accessible']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.managementPct=0;s.operations.reservePerUnit=0});close(f.monthlyRent,17000)});
test('stabilized occupancy is conservative with vacancy',()=>{const f=calc(s=>{s.unitmix.units=[['A',1,500,1000,0,'Market']];s.unitmix.vacancyPct=3;s.unitmix.stabilizedOccupancy=90;s.operations.managementPct=0;s.operations.reservePerUnit=0});close(f.residentialEgi,10800)});
test('commercial schedule is separate',()=>{const f=calc(s=>{s.unitmix.units=[];s.operations.managementPct=0;s.operations.reservePerUnit=0;s.operations.commercial.annualBaseRent=120000;s.operations.commercial.annualRecoveries=12000;s.operations.commercial.vacancyPct=5;s.operations.commercial.stabilizedOccupancy=95;s.operations.commercial.badDebtPct=0;s.operations.commercial.managementPct=4;s.operations.commercial.reserveAnnual=2000;s.operations.commercial.expenses=[['x',30000]]});close(f.commercialEgi,125400);close(f.commercialNoi,88384)});
test('residential and commercial LTC split',()=>{const f=calc(s=>{s.budget.costs=[['Land','x',1000000,'Land'],['Hard','x',9000000,'Hard']];s.budget.constructionContingencyPct=0;s.budget.softContingencyPct=0;s.budget.developerFeePct=0;s.cmhc.nonResidentialCostPct=20;s.financing.requestedLtc=90;s.financing.requestedNonResidentialLtc=75;s.financing.includeCalculatedCarry='No';s.unitmix.units=[['A',100,700,5000,0,'Market']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.managementPct=0;s.operations.reservePerUnit=0;s.operations.expenses=[];s.operations.commercial.annualBaseRent=1000000;s.operations.commercial.vacancyPct=0;s.operations.commercial.stabilizedOccupancy=100;s.operations.commercial.badDebtPct=0;s.operations.commercial.managementPct=0;s.operations.commercial.expenses=[]});close(f.residentialLtcLoan,7200000);close(f.nonResidentialLtcLoan,1500000);close(f.ltcLoan,8700000)});
test('actual debt service lower than qualification at lower rate',()=>{const f=calc(s=>{s.financing.interestRate=4;s.financing.qualificationRate=6;s.financing.includeCalculatedCarry='No';s.unitmix.units=[['A',50,700,3000,0,'Market']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.managementPct=0;s.operations.reservePerUnit=0;s.operations.expenses=[];s.budget.costs=[['Hard','x',5000000,'Hard']];s.budget.constructionContingencyPct=0;s.budget.softContingencyPct=0;s.budget.developerFeePct=0});assert.ok(f.actualDebt<f.qualifyingDebt);assert.ok(f.actualDcr>f.qualifyingDcr)});
test('construction carry responds to duration and rate',()=>{const a=calc(s=>{s.budget.costs=[['Hard','x',5000000,'Hard']];s.budget.constructionContingencyPct=0;s.budget.developerFeePct=0;s.returns.constructionMonths=12;s.financing.constructionInterestRate=5;s.unitmix.units=[['A',50,700,3000,0,'Market']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.managementPct=0;s.operations.reservePerUnit=0;s.operations.expenses=[]}),b=calc(s=>{s.budget.costs=[['Hard','x',5000000,'Hard']];s.budget.constructionContingencyPct=0;s.budget.developerFeePct=0;s.returns.constructionMonths=24;s.financing.constructionInterestRate=7;s.unitmix.units=[['A',50,700,3000,0,'Market']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.managementPct=0;s.operations.reservePerUnit=0;s.operations.expenses=[]});assert.ok(b.calculatedCarry>a.calculatedCarry)});
test('rent and expense growth change projected NOI',()=>{const f=calc(s=>{s.unitmix.units=[['A',10,700,2000,0,'Market']];s.unitmix.vacancyPct=0;s.unitmix.stabilizedOccupancy=100;s.operations.expenses=[['x',100000]];s.operations.managementPct=0;s.operations.reservePerUnit=0;s.unitmix.rentGrowthPct=3;s.operations.expenseGrowthPct=1});assert.ok(f.annualNois[1]>f.annualNois[0])});
test('sale costs reduce proceeds',()=>{const a=calc(s=>{s.returns.saleCostsPct=0;s.financing.includeCalculatedCarry='No'}),b=calc(s=>{s.returns.saleCostsPct=5;s.financing.includeCalculatedCarry='No'});assert.ok(b.netSaleProceeds<=a.netSaleProceeds)});
test('discount rate changes NPV',()=>{const a=calc(s=>{s.returns.discountRate=5;s.financing.includeCalculatedCarry='No'}),b=calc(s=>{s.returns.discountRate=15;s.financing.includeCalculatedCarry='No'});assert.ok(b.projectNpv<=a.projectNpv||(!a.investedEquity&&!b.investedEquity))});
test('lease-up cashflow length uses timing inputs',()=>{const f=calc(s=>{s.returns.constructionMonths=18;s.returns.leaseupMonths=9;s.returns.holdYears=2;s.unitmix.preleasePct=100;s.operations.commercial.annualBaseRent=0;s.financing.includeCalculatedCarry='No'});assert.equal(f.monthlyCashFlows.length,18+9+24)});
test('absorption can extend effective lease-up',()=>{const f=calc(s=>{s.returns.constructionMonths=12;s.returns.leaseupMonths=3;s.returns.holdYears=1;s.unitmix.units=[['A',20,700,2000,0,'Market']];s.unitmix.preleasePct=0;s.unitmix.stabilizedOccupancy=100;s.unitmix.absorptionRate=2;s.operations.commercial.annualBaseRent=120000;s.operations.commercial.preleasePct=0;s.operations.commercial.stabilizedOccupancy=100;s.operations.commercial.absorptionMonths=14;s.financing.includeCalculatedCarry='No'});assert.equal(f.effectiveLeaseupMonths,14);assert.equal(f.monthlyCashFlows.length,12+14+12)});
test('all core outputs finite under extreme inputs',()=>{const f=calc(s=>{s.unitmix.vacancyPct=250;s.unitmix.badDebtPct=250;s.unitmix.stabilizedOccupancy=-20;s.cmhc.nonResidentialCostPct=500;s.financing.requestedLtc=500;s.financing.requestedNonResidentialLtc=500;s.returns.discountRate=-150});for(const k of ['totalCost','noi','loan','equity','projectNpv','exitValue','actualDebt','qualifyingDebt'])assert.ok(Number.isFinite(f[k]),k)});
console.log(`Completed ${count} tests`);
